Testcase1:
  source:
    pkg: genie.libs.sdk
    class: triggers.blitz.blitz.Blitz
  test_sections:
    - configure_commands:
      - configure:
          device: R1
          command: |
              router ospf 6
              router-id 1.1.1.1
