all:
        vars:
                ansible_user: rayka
        children:
                router:
                        hosts:
                                router1:
                                        ansible_host: 192.168.1.95
                                router2:
                                        ansible_host: 192.168.1.96
                        vars:
                                ansible_connection: network_cli
                                ansible_network_os: ios
                server:
                        hosts:
                                centos:
                                        ansible_host: 192.168.1.100 
                                        ansible_user: root

