#!/bin/bash

notify1="state down"
notify2="state up"
notify3="BGP: Peer"

tail -n 0 -F /var/log/syslog | \
while read LINE
do
echo "$LINE" | egrep -q "$notify1|$notify2|$notify3"
if [ $? = 0 ]
then
echo -e "$LINE" | tee -a >>mynotifylog >(mail -s "TV1-Netzwerkbenachrichtigung: $LINE" masadpour@yahoo.com) >(mail -s "TV1-Netzwerkbenachrichtigung: $LINE" majid.asadpoor@gmail.com)
fi
done