#!/bin/bash

notify1="state down"
notify2="state up"
notify3="BGP: Peer"

tail -n 0 -F /var/log/syslog | \
while read LINE
do
echo "$LINE" | egrep -q "$notify1|$notify2|$notify3"
if [ $? = 0 ]
then
#echo -e "$LINE" | tee -a >>mynotifylog >(mail -s "TV1-Netzwerkbenachrichtigung: $LINE" m.asadpoor@tv1.eu) >(mail -s "TV1-Netzwerkbenachrichtigung: $LINE" c2ce98a2x.tv1.eu@emea.teams.ms)
echo -e "$LINE" | tee -a >>mynotifylog >(mail -s "TV1-Netzwerkbenachrichtigung: $LINE" t.bernhard@tv1.eu) >(mail -s "TV1-Netzwerkbenachrichtigung: $LINE" s.schlichtmeier@tv1.eu) >(mail -s "TV1-Netzwerkbenachrichtigung: $LINE" m.asadpoor@tv1.eu)
fi
done