name: BACKUP

on:
  workflow_dispatch:

jobs:
  run-backup:
    runs-on: ubuntu-22.04

    env:
      DEVICE_USERNAME: ${{ secrets.DEVICE_USERNAME }}
      DEVICE_PASSWORD: ${{ secrets.DEVICE_PASSWORD }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Make Backup script executable
        run: chmod +x backup.py

      - name: Install Python and pip
        run: |
          apt-get update
          apt-get install -y python3 python3-pip

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install nornir nornir-utils nornir-jinja2 netmiko jinja2 nornir-scrapli

      - name: Copy SSH legacy config
        run: |
          mkdir -p /etc/ssh/ssh_config.d
          cp config/legacy.conf /etc/ssh/ssh_config.d/legacy.conf

      #- name: Sleep short
      #  run: sleep 300
        
      - name: Run Backup script
        run: |
          echo "The workspace directory is: ${{ github.workspace }}"
          cd ${{ github.workspace }}
          ./backup.py

      - name: Commit generated configs (if any)
        run: |
          echo "Listing generated configs in ./backup:"
          ls -l ./backup || echo "No configs found"

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          CHANGED=$(git status --porcelain ./backup)
          if [ -n "$CHANGED" ]; then
            git add ./backup
            git commit -m "Add/update generated MAB configs"
            git push origin HEAD
          else
            echo "No changes to commit"
          fi

