---
  all:
    vars:
      ansible_user: rayka
      ansible_password: rayka-co.com
      ansible_port: 22
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.ios.ios
    children:
      csr:
        hosts:
          csr1:
          csr2:
      router:
        children:
          cisco:
            hosts:
              core1:
              core2:
              csr1:
              csr2:
          junos:
            vars:
              ansible_user: root
              ansible_port: 2222
            hosts:
              access1:
                vars:
                  ansible_host: 10.10.10.1
                  ansible_user: sara
                  ansible_port: 2222
              access2:
      srx:
        hosts:
          srx1:
          srx2:
          srx3:
