---

R1:
  hostname: "192.168.2.91"
  groups:
    - cisco
  data:
    type: router
    city: babolsar
    core: False
    as_number: 65001

R2:
  hostname: "192.168.2.92"
  groups:
    - cisco
  data:
    type: switch
    city: munich
    core: True
    as_number: 65002

R3:
  hostname: "192.168.200.101"
  groups:
    - juniper
  data:
    type: switch
    city: frankfurt
    core: True
    as_number: 65002
