#! /bin/bash

`awk '{print $1}' tasks | sed '1,3d' | sed '/^$/d' > ./tmp/newtasks`
`awk 'BEGIN{FS="="} {print $2}' illegalprocesses | sed 's/^.//g' | sed 's/.$//g' | sed '/^$/d' > ./tmp/newillegalprocesses`

while read process; do
  while read task; do
    echo $task | grep $process 2>/dev/null
    #echo "task ............ $task"
    #echo "process ............$process"
  done < ./tmp/newtasks
done < ./tmp/newillegalprocesses
