---
- hosts: router
  gather_facts: false
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: rayka
      password: rayka-co.ir

  tasks:
    - name: change config
      ios_config:
        lines: hostname {{ inventory_hostname }}
        provider: "{{ cli }}"
      notify: config_changed
      register: response

  handlers:
    - name: "changes.."
      listen: config_changed
      debug:
        msg: "{{ response }}"
