---
- hosts: csr
  gather_facts: false
  connection: network_cli

  tasks:
    - name: test ios_command module
      ios_command:
        commands: 
          - show version
          - show interfaces
        wait_for: 
          - result[0] contains ios
          - result[1] contains Ethernet
