---
- name: Load configuration from a local file and commit
  hosts: kheili morageb bash
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no


  tasks:
   - name: Load configuration from a local file and commit
     juniper_junos_config:
       load: "override"
       src: "~/IaC//{{ inventory_hostname }}.xml"
#        dest_dir: "{{ playbook_dir }}"
#    - name: "Print result"
#      debug:
#        var: response
