---
- name: Get IOS configuration
  hosts: kheili moragheb bash
  gather_facts: no
  connection: local

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{user}}"
      #password: "{{password}}"
      authorize: yes
      #auth_pass: "{{password}}"


  tasks:
    - name: COPY RUNNING CONFIG TO ROUTER
      command: scp ./backup/{{inventory_hostname}}.config {{inventory_hostname}}:/{{inventory_hostname}}.config

    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.config force


# https://iac.goffinet.org/ansible-network/sauvegarder-restaurer-configuration-router/
