---
- name: Get IOS configuration
  hosts: ios 
  gather_facts: true
  connection: local

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{user}}"
      #password: "{{password}}"
      authorize: yes
      #auth_pass: "{{password}}"

  tasks:
    - name: show run 
      ios_command:
        authorize: yes
        commands:
          - show run 
        provider: "{{ cli }}"
      register: config


    - name: save output to ~/IaC/
      copy: 
       content: "{{ config.stdout[0] }}"
       dest: "~/IaaC//show_run_{{ inventory_hostname }}.txt"

