---
- hosts: router
  gather_facts: false
  connection: local
  vars:
    var_str: "hello world"

  tasks:
    - name: configure dhcp server with loop fucntion
      debug:
        msg: "{{var_str}} majid"
      
