---

R1:
  hostname: "192.168.2.91"
#  username: "rayka"
#  password: "rayka-co.ir"
  groups:
    - cisco
#  extras:
#    use_keys: true
#    key_file: "/home/coder/.ssh/id_rsa"
  data:
    community: rayka
#R2:
#  hostname: "192.168.2.92"
#  username: "rayka"
#  password: "rayka-co.ir"
#  groups:
#    - cisco
#  data:
#    community: rayka

#R3:
#  hostname: "192.168.2.93"
#  username: "rayka"
#  password: "rayka-co.ir"
#  groups:
#    - juniper
#  data:
#    community: rayka-co.com
