---

R1:
  hostname: "192.168.1.11"
#  username: "rayka"
#  password: "rayka-co.com"
  groups:
    - cisco
    - router
R2:
  hostname: "192.168.1.12"
#  username: "rayka"
#  password: "rayka-co.com"
  groups:
    - cisco
    - router
R3:
  hostname: "192.168.1.13"
  username: "RAYKA"
  password: "RAYKA-CO.COM"
  groups:
    - juniper
    - router
